### ISSUE TITLE
Incorrect frequency in CLANNAD's (English Ver.) sounds

### ISSUE THREAD

**Issue by gikari** [eglaysher/rlvm#82] opened 2018-04-20 22:27 UTC
When I start CLANNAD in rlvm the main menu appears, and the background music sounds weird - differently from normal execution on windows native RealLive interpreter. I discovered that it happens because somehow rlvm version is an tranforemed by frequency sound file. I extracted bgm .nwa to .wav with  [Arc Unpacker](https://github.com/vn-tools/arc_unpacker). It appears, that the original sound file is 44100 Hz, but if I transformed it with Audacity to 48000 Hz it begins to sound exactly like in rlvm. It happens to all music files. 

It seems it is connected to some non-needed frequency transformation in code, but I am not sure. #72

**Comment by eglaysher** [comment] 2018-04-20 23:47
This is basically a dupe of #72, which is a problem in an external dependency which I was never able to work around.

**Closed by eglaysher** 2018-04-20 23:47 UTC
