### ISSUE TITLE
Voices cannot be enabled in Clannad FV

### ISSUE THREAD

**Issue by muah** [eglaysher/rlvm#61] opened 2014-09-23 22:30 UTC
In order to hear the voices in Clannad, one needs to set the name to okazaki tomoya, however that is impossible due to input fields not working. The name field seems to be empty by default, and the button to set the name to the default one doesn't seem to work either. I have not installed any English translation patches.
I wonder if this could be worked around.

**Comment by eglaysher** [comment] 2016-06-13 22:31
(Closing since no one ever mentioned this non-reproducible issue ever again.)

**Closed by eglaysher** 2016-06-13 22:31 UTC
